name: 'Infrastructure pull request trigger'

on:
  push:
    paths:
      - 'staging/infrastructure/gke/**'
    branches:
      - master
  pull_request:

jobs:
  the_job:
    uses: ./.github/workflows/base.yaml
    with:
      tf_workspace: staging/infrastructure/gke
    secrets:
      gcp_credentials: ${{ vars.GCP_CREDENTIALS }}
