name: 'Istio pull request trigger'

on:
  push:
    paths:
      - 'staging/infrastructure/istio/**'
    branches:
      - master
  pull_request:

jobs:
  the_job:
    uses: ./.github/workflows/base.yaml
    with:
      tf_workspace: staging/infrastructure/istio
    secrets:
      gcp_credentials: ${{ vars.GCP_CREDENTIALS }}
      vault_address: ${{ vars.VAULT_ADDR }}
      vault_token: ${{ vars.VAULT_TOKEN }}
