name: 'Mailbox pull request trigger'

on:
  push:
    paths:
      - 'staging/wms/mailbox/**'
    branches:
      - master
  pull_request:

jobs:
  the_job:
    uses: ./.github/workflows/base.yaml
    with:
      tf_workspace: staging/wms/mailbox
    secrets:
      # This is holding the content of mailboc-gcp-token.json
      gcp_credentials: ${{ vars.GCP_CREDENTIALS }}
      vault_address: ${{ vars.VAULT_ADDR }}
      vault_token: ${{ vars.VAULT_TOKEN }}
