name: 'Mailbox pull request trigger'

on:
  push:
    paths:
      - 'staging/wms/mailbox/**'
    branches:
      - na
  pull_request:

jobs:
  the_job:
    uses: ./.github/workflows/base.yaml
    with:
      tf_workspace: staging/wms/mailbox
    secrets:
      # This is holding the content of mailboc-gcp-token.json
      gcp_credentials: ${{ vars.GCP_CREDENTIALS }}
      pg_username: ${{ vars.PG_USERNAME }}
      pg_password: ${{ vars.PG_PASSWORD }}
