name: 'Terraform pull request trigger'

on:
  push:
    paths:
      - 'staging/terraform/**'
    branches:
      - master
  pull_request:

jobs:
  the_job:
    uses: ./.github/workflows/base.yaml
    with:
      tf_workspace: staging/terraform
    secrets:
      # This is holding the content of mailboc-gcp-token.json
      gcp_credentials: ${{ vars.GCP_CREDENTIALS }}
      pg_username: ''
      pg_password: ''
