name: 'Vault pull request trigger'

on:
  push:
    paths:
      - 'staging/vault/**'
    branches:
      - na
  pull_request:

jobs:
  the_job:
    uses: ./.github/workflows/base.yaml
    with:
      tf_workspace: staging/vault
    secrets:
      # This is holding the content of mailboc-gcp-token.json
      gcp_credentials: ${{ vars.GCP_CREDENTIALS }}
